CREATE DATABASE customer_behavior;

SELECT * FROM customer LIMIT 5;

-- Q1. What is the total revenue generated by male vs. female customers?

select gender, SUM(purchase_amount) AS revenue
from customer
group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as "Avg Product Rating"
from customer
group by item_purchased
order by avg(review_rating) DESC limit 5;			# this is the correct syntax, orders by avg(review_rating), we used desc as it asks highest average review rating, limit is commonly used with group by

select item_purchased, avg(review_rating) as "Avg Product Rating"
from customer
group by item_purchased
order by item_purchased DESC limit 5;			# orders by alphabetically


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, avg(purchase_amount) as "Avg Purchase Amount"
from customer
group by shipping_type
having shipping_type IN('Standard','Express');


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status, count(customer_id) as 'Total Customers', round(avg(purchase_amount), 2) as 'Avg Spend', round(sum(purchase_amount), 2) as 'Total Revenue'
from customer
group by subscription_status;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
	ROUND((sum(CASE WHEN discount_applied = 'YES' then 1 else 0 END) / count(*)) * 100, 2) AS discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END
    AS customer_segment
FROM customer)

select customer_segment, count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- Q10. What is the revenue contribution of each age group?

select age_group, sum(purchase_amount) as revenue
from customer
group by age_group
order by revenue DESC;
